import React from 'react';

function StartContainer() {
    return (
        <div className = 'main'>
            <h2>Before you start</h2>
            <h3>Why PC? And why build your own?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <p>Mauris suscipit, orci non feugiat feugiat, dolor dolor hendrerit mauris, ut dignissim erat ipsum a orci. Donec sed ante in tortor egestas porttitor. Ut ut sodales quam. Fusce ac felis risus. Aliquam placerat, ipsum quis pulvinar blandit, metus lorem dictum lectus, in ultrices est lorem sed sem. Etiam fermentum commodo justo id posuere. Pellentesque finibus ac tellus at sagittis. Vestibulum id nunc id est volutpat auctor et non nulla. Donec congue justo sit amet odio semper laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras consectetur ligula vel quam feugiat, a pharetra ex accumsan.</p>
            <p>Fusce quam mi, fermentum porta nisi sit amet, molestie bibendum enim. Mauris a tortor ullamcorper, pulvinar lorem id, iaculis ex. Quisque leo nunc, vestibulum quis nulla id, accumsan euismod massa. Maecenas pulvinar tellus eget tempor porttitor. Suspendisse ornare quam a pulvinar sagittis. In hac habitasse platea dictumst. Integer viverra quam tellus, ut gravida nunc scelerisque non. Sed nec porta est. Donec vel erat quis purus iaculis tincidunt sed ut ligula. Vestibulum ornare rhoncus nunc interdum condimentum. Suspendisse molestie massa vitae mauris aliquet ultrices. Aliquam id justo et sem efficitur fringilla non nec felis.</p>
            <h3>Set Expectations</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>Planning</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>Building</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>....Now What?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
        </div>
    )
}

export default StartContainer;  