import React from 'react';
import { Link } from 'react-router-dom';

function PlanningContainer() {
    return (
        <div className = 'main'>
            <h2>Planning</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>Budgeting</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <Link to = '/planning/budget-tool'><button>Go to the budget tool</button></Link>
            <h3>Picking parts</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>Example Builds</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
            <h3>Plan for periherals</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a lacinia purus. Mauris congue elit sit amet justo sollicitudin porttitor. Vivamus quis vulputate nulla. Curabitur et dui at eros condimentum congue quis id sapien. Fusce mi odio, aliquam eu orci non, mattis mollis leo. Vivamus egestas magna eget luctus ultricies. Vivamus sodales finibus neque, nec tristique ligula euismod in. Fusce gravida leo vel magna varius, at imperdiet dolor eleifend. Pellentesque tincidunt leo vel libero tempor fringilla. Nunc interdum faucibus dui sit amet mattis. Donec lacinia finibus egestas. Pellentesque scelerisque odio quis orci malesuada mattis. Maecenas laoreet pharetra lectus, a finibus mi cursus vel.</p>
        </div>
    )
}

export default PlanningContainer;